parameters:
    env(DATABASE_URL): pgsql://root:root@localhost:5432/testing_db

doctrine:
    dbal:
        # configure these for your database server
        driver:   pdo_pgsql
        host:     localhost
        port:     5432
        dbname:   testing_db
        user:     root
        password: root
        # With Symfony 3.3, remove the `resolve:` prefix
        url: pgsql://root:root@localhost:5432/testing_db
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
